// *** Generated by OFS compiler version 0.0 *** 
const x = y;
const x = 1;
const x = undefined;
const x = 1;
const x = 1;
const x = 1;
let y = undefined;
const test = x;
const test2 = 666;
const luis = [23, test, [1]];
